/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package d6;

import java.util.concurrent.*;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws Exception {
        // Executor executor = Executors.newSingleThreadExecutor();
        // executor.execute(() -> System.out.println("Hello World"));
        ExecutorService executorService = Executors.newFixedThreadPool(10);
        Future<String> future = executorService.submit(() -> "Hello World");

        String result = future.get();
        System.out.println("[FUTURE] :: " + result);
    }
}
