/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package d4;

import java.net.*;
import java.io.*;
import java.util.*;

class URLDemo {

    public static void viewURL() {
        try {
            URL url = new URL("https://google.com/search?q=javatpoint&oq=javatpoint&sourceid=chrome&ie=UTF-8");

            System.out.println("Protocol :: " + url.getProtocol());
            System.out.println("Host Name :: " + url.getHost());
            System.out.println("Port Number :: " + url.getPort());
            System.out.println("Default Port Number :: " + url.getDefaultPort());
            System.out.println("Query String :: " + url.getQuery());
            System.out.println("Path :: " + url.getPath());
            System.out.println("File :: " + url.getFile());
        } catch (Exception e) {
            System.err.println("Exception bro!");
        }
    }

}

class URLConnDemo {

    public static void viewURLConn() {
        try {
            URL url = new URL("https://javatpoint.com/java-tutorial");
            URLConnection urlConnection = url.openConnection();
            InputStream inputStream = urlConnection.getInputStream();

            StringBuffer sb = new StringBuffer();
            String content;
            int counter = 0;
            int c;
            while ((c = inputStream.read()) > 0 && c != -1) {
                sb.append((char)c);
                counter++;
            }
            System.out.println(sb.toString());
        } catch (Exception e) {
            System.err.println("Exception bro!");
        }
    }

}

class HttpConnDemo {

    public static void demo() {
        try {
            URL url = new URL("https://javatpoint.com/java-tutorial");
            HttpURLConnection httpConn = (HttpURLConnection) url.openConnection();

            for (int i = 0; i <= 8; ++i) {
                System.out.println(httpConn.getHeaderFieldKey(i) + " :: " + httpConn.getHeaderField(i));
            }
            httpConn.disconnect();
        } catch (Exception e) {
            System.err.println("Exception bro!");
        }
    }

}

class IPAddr {

    public static void demo() {
        try {
            InetAddress ip = InetAddress.getByName("www.javatpoint.com");
            System.out.println("Host Name :: " + ip.getHostName());
            System.out.println("IP Address :: " + ip.getHostAddress());
        } catch (Exception e) {
            System.err.println("Exception bro!");
        }
    }

    public static void verboseDemo() {
        try {
            InetAddress ip = Inet4Address.getByName("www.javatpoint.com");
            InetAddress ips[] = InetAddress.getAllByName("www.javatpoint.com");
            byte addr[] = {72, 3, 2, 12};

            System.out.println("IP :: " + ip);
            System.out.println("IPs :: " + ips);

            InetAddress ip2 = InetAddress.getByAddress(addr);
            System.out.println("IP :: " + ip2);

            print("Address :: " + Arrays.toString(ip.getAddress()));
            print("Host Address :: " + ip.getHostAddress());
            print("AnyLocalAddress :: " + ip.isAnyLocalAddress());
            print("LinkLocalAddress :: " + ip.isLinkLocalAddress());
            print("LoopbackAddress :: " + ip.isLoopbackAddress());
            print("isMCGlobal :: " + ip.isMCGlobal());
            print("isMCNodeLocal :: " + ip.isMCNodeLocal());
            print("isMCOrgLocal :: " + ip.isMCOrgLocal());
            print("isMCSiteLocal :: " + ip.isMCSiteLocal());
            print("isMulticastAddress :: " + ip.isMulticastAddress());
            print("isSiteLocalAddress :: " + ip.isSiteLocalAddress());
            print("hasCode :: " + ip.hashCode());
            print("ip1 == ip2 :: " + ip.equals(ip2));
        } catch (Exception e) {
            System.err.println("Exception bro!");
        }
    }

    public static void print(String arg) {
        System.out.println(arg);
    }

}

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // URLDemo.viewURL();
        // URLConnDemo.viewURLConn();
        // HttpConnDemo.demo();
        // IPAddr.demo();
        IPAddr.verboseDemo();
    }
}
